-- MySQL Script generated by MySQL Workbench
-- 02/11/15 19:32:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cursos_dmi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cursos_dmi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cursos_dmi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cursos_dmi` ;

-- -----------------------------------------------------
-- Table `cursos_dmi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos_dmi`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `nombreProfesor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos_dmi`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`cursos` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombreCurso` VARCHAR(45) NOT NULL,
  `codigoCurso` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `idProfesor_idx` (`idProfesor` ASC),
  CONSTRAINT `idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `cursos_dmi`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos_dmi`.`usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`usuario_curso` (
  `idUsuario_curso` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idcurso` INT NOT NULL,
  PRIMARY KEY (`idUsuario_curso`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idcurso_idx` (`idcurso` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cursos_dmi`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcurso`
    FOREIGN KEY (`idcurso`)
    REFERENCES `cursos_dmi`.`cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos_dmi`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `nombreNota` VARCHAR(45) NOT NULL,
  `porcentaje` FLOAT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `idCurso_idx` (`idCurso` ASC),
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `cursos_dmi`.`cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos_dmi`.`nota_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos_dmi`.`nota_Usuario` (
  `idNota_usuario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idNota` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idNota_usuario`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idCurso_idx` (`idCurso` ASC),
  INDEX `idNota_idx` (`idNota` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cursos_dmi`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `cursos_dmi`.`cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNota`
    FOREIGN KEY (`idNota`)
    REFERENCES `cursos_dmi`.`nota` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
